/* ═══ TaazaBandi — Seed Data for Hyderabad 500075 ═══ */

import { Bundle, Zone, Slot, AddOn } from './types';

// ─── Zones (Hyderabad 500075) ───
export const zones: Zone[] = [
  {
    id: 'zone-a',
    name: 'Zone A: Jubilee Hills',
    pincode: '500075',
    areas: ['Jubilee Hills', 'Filmnagar', 'Yousufguda'],
    morning_slot_capacity: 250,
    evening_slot_capacity: 150,
    is_active: true,
  },
  {
    id: 'zone-b',
    name: 'Zone B: Banjara Hills',
    pincode: '500075',
    areas: ['Banjara Hills', 'Road No. 1-14', 'Panjagutta'],
    morning_slot_capacity: 200,
    evening_slot_capacity: 120,
    is_active: true,
  },
  {
    id: 'zone-c',
    name: 'Zone C: Madhapur',
    pincode: '500075',
    areas: ['Madhapur', 'Hitec City', 'Kondapur'],
    morning_slot_capacity: 300,
    evening_slot_capacity: 180,
    is_active: true,
  },
];

// ─── Bundles ───
export const bundles: Bundle[] = [
  {
    id: 'bundle-family',
    name: 'Family Pack',
    name_te: 'కుటుంబ ప్యాక్',
    price: 299,
    original_price: 450,
    description: 'Perfect for a family of 4. Fresh vegetables for 3-4 days of cooking. All essentials included!',
    image_url: '/images/family-bundle.png',
    serves: 'Family of 4',
    frequency: 'Every 3 days',
    is_active: true,
    is_popular: true,
    tag: 'Most Popular',
    vegetables: [
      { name: 'Potato', name_te: 'బంగాళాదుంప', quantity: '2 kg', icon: '🥔' },
      { name: 'Onion', name_te: 'ఉల్లిపాయ', quantity: '1 kg', icon: '🧅' },
      { name: 'Tomato', name_te: 'టమోటా', quantity: '1 kg', icon: '🍅' },
      { name: 'Green Chilli', name_te: 'పచ్చిమిర్చి', quantity: '250g', icon: '🌶️' },
      { name: 'Cauliflower', name_te: 'క్యాలీఫ్లవర్', quantity: '1 piece', icon: '🥦' },
      { name: 'Spinach', name_te: 'పాలకూర', quantity: '1 bunch', icon: '🥬' },
      { name: 'Carrot', name_te: 'క్యారెట్', quantity: '500g', icon: '🥕' },
      { name: 'Capsicum', name_te: 'క్యాప్సికమ్', quantity: '250g', icon: '🫑' },
    ],
  },
  {
    id: 'bundle-single',
    name: 'Single Pack',
    name_te: 'సింగిల్ ప్యాక్',
    price: 199,
    original_price: 280,
    description: 'Ideal for bachelors & couples. Compact pack with all daily essentials for 3-4 days.',
    image_url: '/images/single-bundle.png',
    serves: '1-2 persons',
    frequency: 'Every 3 days',
    is_active: true,
    tag: 'Best Value',
    vegetables: [
      { name: 'Potato', name_te: 'బంగాళాదుంప', quantity: '1 kg', icon: '🥔' },
      { name: 'Onion', name_te: 'ఉల్లిపాయ', quantity: '500g', icon: '🧅' },
      { name: 'Tomato', name_te: 'టమోటా', quantity: '500g', icon: '🍅' },
      { name: 'Green Chilli', name_te: 'పచ్చిమిర్చి', quantity: '100g', icon: '🌶️' },
      { name: 'Coriander', name_te: 'కొత్తిమీర', quantity: '1 bunch', icon: '🌿' },
      { name: 'Lady Finger', name_te: 'బెండకాయ', quantity: '250g', icon: '🫛' },
    ],
  },
  {
    id: 'bundle-weekly',
    name: 'Weekly Mega Pack',
    name_te: 'వారపు మెగా ప్యాక్',
    price: 599,
    original_price: 900,
    description: 'Complete weekly supply for a large family. 15+ vegetables, zero trips to mandi!',
    image_url: '/images/weekly-bundle.png',
    serves: 'Family of 5-6',
    frequency: 'Weekly',
    is_active: true,
    tag: 'Max Savings',
    vegetables: [
      { name: 'Potato', name_te: 'బంగాళాదుంప', quantity: '3 kg', icon: '🥔' },
      { name: 'Onion', name_te: 'ఉల్లిపాయ', quantity: '2 kg', icon: '🧅' },
      { name: 'Tomato', name_te: 'టమోటా', quantity: '2 kg', icon: '🍅' },
      { name: 'Green Chilli', name_te: 'పచ్చిమిర్చి', quantity: '500g', icon: '🌶️' },
      { name: 'Cauliflower', name_te: 'క్యాలీఫ్లవర్', quantity: '2 pieces', icon: '🥦' },
      { name: 'Spinach', name_te: 'పాలకూర', quantity: '2 bunches', icon: '🥬' },
      { name: 'Carrot', name_te: 'క్యారెట్', quantity: '1 kg', icon: '🥕' },
      { name: 'Capsicum', name_te: 'క్యాప్సికమ్', quantity: '500g', icon: '🫑' },
      { name: 'Coriander', name_te: 'కొత్తిమీర', quantity: '2 bunches', icon: '🌿' },
      { name: 'Lady Finger', name_te: 'బెండకాయ', quantity: '500g', icon: '🫛' },
      { name: 'Brinjal', name_te: 'వంకాయ', quantity: '500g', icon: '🍆' },
      { name: 'Bottle Gourd', name_te: 'సొరకాయ', quantity: '1 piece', icon: '🥒' },
      { name: 'Beans', name_te: 'బీన్స్', quantity: '250g', icon: '🫘' },
      { name: 'Ginger', name_te: 'అల్లం', quantity: '200g', icon: '🫚' },
      { name: 'Garlic', name_te: 'వెల్లుల్లి', quantity: '200g', icon: '🧄' },
    ],
  },
];

export const addOns: AddOn[] = [
  { id: 'addon-dhaniya', name: 'Coriander', name_te: 'కొత్తిమీర', price: 10, unit: 'bunch', icon: '🌿', is_available: true },
  { id: 'addon-nimbu', name: 'Lemon', name_te: 'నిమ్మకాయ', price: 15, unit: '4 pieces', icon: '🍋', is_available: true },
  { id: 'addon-mirch', name: 'Green Chilli', name_te: 'పచ్చిమిర్చి', price: 10, unit: '100g', icon: '🌶️', is_available: true },
  { id: 'addon-adrak', name: 'Ginger', name_te: 'అల్లం', price: 20, unit: '100g', icon: '🫚', is_available: true },
  { id: 'addon-pudina', name: 'Mint', name_te: 'పుదీనా', price: 10, unit: 'bunch', icon: '🌱', is_available: true },
  { id: 'addon-curry', name: 'Curry Leaves', name_te: 'కరివేపాకు', price: 5, unit: 'sprig', icon: '🍃', is_available: true },
];

// ─── Today's Slots ───
const today = new Date().toISOString().split('T')[0];

export const todaySlots: Slot[] = [
  {
    id: 'slot-m-a',
    zone_id: 'zone-a',
    zone_name: 'Zone A: Jubilee Hills',
    slot_type: 'morning',
    slot_label: '6:00 AM - 9:00 AM',
    date: today,
    total_capacity: 250,
    booked_count: 187,
    is_full: false,
    vans_assigned: 5,
  },
  {
    id: 'slot-e-a',
    zone_id: 'zone-a',
    zone_name: 'Zone A: Jubilee Hills',
    slot_type: 'evening',
    slot_label: '5:00 PM - 8:00 PM',
    date: today,
    total_capacity: 150,
    booked_count: 42,
    is_full: false,
    vans_assigned: 3,
  },
  {
    id: 'slot-m-b',
    zone_id: 'zone-b',
    zone_name: 'Zone B: Banjara Hills',
    slot_type: 'morning',
    slot_label: '6:00 AM - 9:00 AM',
    date: today,
    total_capacity: 200,
    booked_count: 200,
    is_full: true,
    vans_assigned: 4,
  },
  {
    id: 'slot-e-b',
    zone_id: 'zone-b',
    zone_name: 'Zone B: Banjara Hills',
    slot_type: 'evening',
    slot_label: '5:00 PM - 8:00 PM',
    date: today,
    total_capacity: 120,
    booked_count: 78,
    is_full: false,
    vans_assigned: 2,
  },
  {
    id: 'slot-m-c',
    zone_id: 'zone-c',
    zone_name: 'Zone C: Madhapur',
    slot_type: 'morning',
    slot_label: '6:00 AM - 9:00 AM',
    date: today,
    total_capacity: 300,
    booked_count: 156,
    is_full: false,
    vans_assigned: 6,
  },
  {
    id: 'slot-e-c',
    zone_id: 'zone-c',
    zone_name: 'Zone C: Madhapur',
    slot_type: 'evening',
    slot_label: '5:00 PM - 8:00 PM',
    date: today,
    total_capacity: 180,
    booked_count: 23,
    is_full: false,
    vans_assigned: 3,
  },
];

// ─── Service pincode ───
export const SERVICE_PINCODE = '500075';
export const SERVICE_CITY = 'Hyderabad';
